apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate 
  template: 
    metadata: 
      labels: 
        app: mysql
    spec: 
      containers:
        - name: mysql
          image: mdcrepositorychiroli.azurecr.io/mysql-copyinitsql:v1
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Mindthegap@0823*
            - name: MYSQL_DATABASE
              value: test_db
          ports:
            - containerPort: 3306
              name: mysql  
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql                                               
      volumes: 
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: azure-managed-disk-pvc
      imagePullSecrets:
        - name: acr-secret